# Generated by Django 5.2.8 on 2025-11-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundevilconnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
