# Generated by Django 5.2.8 on 2025-11-13 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundevilconnect', '0002_alter_event_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_flagged', models.BooleanField(verbose_name=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sundevilconnect.club')),
            ],
        ),
    ]
