# Generated by Django 5.2.8 on 2025-11-13 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundevilconnect', '0003_clubcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubcontent',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clubcontent',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
