# Generated by Django 5.2.8 on 2025-11-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundevilconnect', '0006_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('SPORTS', 'Sports'), ('ACADEMIC', 'Academic'), ('SOCIAL', 'Social'), ('FUNDRAISING', 'Fundraising'), ('NETWORKING', 'Networking')], default='SOCIAL', max_length=20),
        ),
    ]
