# Generated by Django 5.2.8 on 2025-11-18 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundevilconnect', '0007_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubcontent',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
