# Generated by Django 5.2.8 on 2025-11-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundevilconnect', '0008_alter_clubcontent_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('M', 'Member'), ('L', 'Leader'), ('R', 'Requested to Join')], default='R', max_length=10),
        ),
    ]
